"""complete user model

Revision ID: 52635f987e6c
Revises: 15df36e81294
Create Date: 2016-04-12 13:39:47.571000

"""

# revision identifiers, used by Alembic.
revision = '52635f987e6c'
down_revision = '15df36e81294'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('newsletter', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('url', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'url')
    op.drop_column('users', 'newsletter')
    op.drop_column('users', 'name')
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
