"""[roles] member added

Revision ID: b0283214af6c
Revises: 52635f987e6c
Create Date: 2016-04-21 13:36:21.942000

"""

# revision identifiers, used by Alembic.
revision = 'b0283214af6c'
down_revision = '52635f987e6c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('member', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'member')
    ### end Alembic commands ###
